url: https://burhanverse.eu.org
baseurl: /xverse.github.io# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Burhan
# typing_text: This will be typed before "Welcome to my Universe".
typing_text: AKA Aqua
