# title: This will be displayed as the website's name in your browser tab.
title: BurhanVerse!
baseurl: "/xverse.github.io"
# username: This will displayed on the landing page as your name.
username: Burhan
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: A Weeb.
# about: T his text will appear below the highlighted head text.
# about: "AKA Aqua, a weeb who is just doing what he likes. In my free time, I code and watch anime. I'm always looking for new ways to learn and grow."